trigger:
- master

pool: 'UKHO Ubuntu 1804'

steps:
- script: |
    cd ubuntu-agents
    sed -i -e "s/<subscriptionID>/$SUBSCRIPTIONID/g" ubuntu-agents.json
    sed -i -e "s/<rgName>/$IMAGERESOURCEGROUP/g" ubuntu-agents.json
    sed -i -e "s/<region>/$REGION/g" ubuntu-agents.json
    sed -i -e "s/<sharedImageGalleryName>/$SHAREDIMAGEGALLERYNAME/g" ubuntu-agents.json
    sed -i -e "s/<imageDefName>/$IMAGEDEFNAME/g" ubuntu-agents.json
    sed -i -e "s/<runOutputName>/$RUNOUTPUTNAME/g" ubuntu-agents.json
    cat ubuntu-agents.json
  displayName: 'String replace variable names'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd ubuntu-agents
      az resource create \
          --resource-group $IMAGERESOURCEGROUP \
          --properties @ubuntu-agents.json \
          --is-full-object \
          --resource-type Microsoft.VirtualMachineImages/imageTemplates \
          -n agent-linux-aib
  displayName: 'Deploy AIB template'

- task: AzureCLI@2 
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az resource invoke-action \
        --resource-group $IMAGERESOURCEGROUP \
        --resource-type  Microsoft.VirtualMachineImages/imageTemplates \
        -n agent-linux-aib \
        --action Run 
  displayName: 'Build the image'    

- task: AzureCLI@2 
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az resource delete \
       --resource-group $IMAGERESOURCEGROUP \
       --resource-type Microsoft.VirtualMachineImages/imageTemplates \
       -n agent-linux-aib
  condition: always()
  displayName: 'Delete the AIB template'    
