trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sed -i -e "s/<subscriptionID>/$SUBSCRIPTIONID/g" agent-linux-aib.json
    sed -i -e "s/<rgName>/$IMAGERESOURCEGROUP/g" agent-linux-aib.json
    sed -i -e "s/<region>/$REGION/g" agent-linux-aib.json
    sed -i -e "s/<sharedImageGalleryName>/$SHAREDIMAGEGALLERYNAME/g" agent-linux-aib.json
    sed -i -e "s/<imageDefName>/$IMAGEDEFNAME/g" agent-linux-aib.json
    sed -i -e "s/<runOutputName>/$RUNOUTPUTNAME/g" agent-linux-aib.json

    sharedImageGalName

    cat agent-linux-aib.json
  displayName: 'String replace variable names'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az resource create \
          --resource-group $IMAGERESOURCEGROUP \
          --properties @agent-linux-aib.json \
          --is-full-object \
          --resource-type Microsoft.VirtualMachineImages/imageTemplates \
          -n agent-linux-aib
  displayName: 'Deploy AIB template'

- task: AzureCLI@2 
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az resource invoke-action \
        --resource-group $IMAGERESOURCEGROUP \
        --resource-type  Microsoft.VirtualMachineImages/imageTemplates \
        -n agent-linux-aib \
        --action Run 
  displayName: 'Build the image'    

- task: AzureCLI@2 
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az resource delete \
       --resource-group $IMAGERESOURCEGROUP \
       --resource-type Microsoft.VirtualMachineImages/imageTemplates \
       -n agent-linux-aib
  condition: always()
  displayName: 'Delete the AIB template'    
