resources:
  pipelines:
    - pipeline: AzDoAgentDrainerBuild
      project: Pipelines
      source: UKHO.AzDoAgentDrainer
      trigger:
        branches:
          include:
            - master

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - '*'
    exclude:
    - README.md

pool: 'UKHO Ubuntu 1804'

container: ukhydrographicoffice/terraform-azure:latest

steps:
- script: |
    cd ubuntu-agent-vm
    sed -i -e "s/<subscriptionID>/$SUBSCRIPTIONID/g" ubuntu-agent-vm-aib.json
    sed -i -e "s/<rgName>/$IMAGERESOURCEGROUP/g" ubuntu-agent-vm-aib.json
    sed -i -e "s/<region>/$REGION/g" ubuntu-agent-vm-aib.json
    sed -i -e "s/<sharedImageGalleryName>/$SHAREDIMAGEGALLERYNAME/g" ubuntu-agent-vm-aib.json
    sed -i -e "s/<imageDefName>/$IMAGEDEFNAME/g" ubuntu-agent-vm-aib.json
    sed -i -e "s/<runOutputName>/$RUNOUTPUTNAME/g" ubuntu-agent-vm-aib.json
    cat ubuntu-agent-vm-aib.json
  displayName: 'String replace variable names'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd ubuntu-agent-vm
      az resource create \
          --resource-group $IMAGERESOURCEGROUP \
          --properties @ubuntu-agent-vm-aib.json \
          --is-full-object \
          --resource-type Microsoft.VirtualMachineImages/imageTemplates \
          -n ubuntu-agent-vm-aib
  displayName: 'Deploy AIB template'

- task: AzureCLI@2 
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az resource invoke-action \
        --resource-group $IMAGERESOURCEGROUP \
        --resource-type  Microsoft.VirtualMachineImages/imageTemplates \
        -n ubuntu-agent-vm-aib \
        --action Run 
  displayName: 'Build the image'    

- task: AzureCLI@2 
  inputs:
    azureSubscription: 'UKHO-TPE'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az resource delete \
       --resource-group $IMAGERESOURCEGROUP \
       --resource-type Microsoft.VirtualMachineImages/imageTemplates \
       -n ubuntu-agent-vm-aib
  condition: always()
  displayName: 'Delete the AIB template'    
