resources:
  pipelines:
    - pipeline: AzDoAgentDrainerBuild
      project: shared-pipelines
      source: UKHO.AzDoAgentDrainer
      trigger:
        branches:
          include:
            - main

trigger:
  branches:
    include:
      - main
  paths:
    include:
    - ubuntu-agent-vm/*
    
schedules:
- cron: "0 5 * * 2"
  displayName: Weekly Build
  branches:
    include:
    - main
  always: true

pr: none

variables:
- group: AzDO-variables
- group: aib-variables
- name: imageDefName
  value: azure-pipelines-image-ubuntu-18-04
- name: runOutputName
  value: aiblinux

jobs:
  - job: cleanup
    pool: 'NautilusBuild'
    steps:
    - pwsh: |
        az login --service-principal --username "$CLIENTID" --password "$CLIENTSECRET" --tenant "$TENANTID"
        az account set --subscription "$SUBSCRIPTIONID"
        $dateLine = (Get-Date).AddMonths(-1)
        $list = (az sig image-version list -g $IMAGERESOURCEGROUP -r $SHAREDIMAGEGALLERYNAME -i $IMAGEDEFNAME -o json | ConvertFrom-Json)
        $splice = $list | Select-Object -Skip 4
        foreach($item in $splice) {
            $publishedDate = Get-Date($item.publishingProfile.publishedDate)
            if($publishedDate -lt $dateLine) {
              $item.name
              Start-Job -ScriptBlock {param($rg, $gallery,$imagedef,$imagename) az sig image-version delete -g $rg -r $gallery -i $imagedef -e $imagename} -ArgumentList @($IMAGERESOURCEGROUP, $SHAREDIMAGEGALLERYNAME,$IMAGEDEFNAME,$($item.name))
            }
        }
      displayName: "Run Cleanup"
      env:
        TENANTID: $(TERRAFORM-TENANT-ID)
        CLIENTID: $(TERRAFORM-CLIENT-ID)
        CLIENTSECRET: $(TERRAFORM-CLIENT-SECRET)
        SUBSCRIPTIONID: $(subscriptionId)
        IMAGERESOURCEGROUP: $(imageResourceGroup)
        SHAREDIMAGEGALLERYNAME: $(sharedImageGalleryName)
        IMAGEDEFNAME: $(imageDefName)
